name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"] # GitHub Actions only supports >= 3.9
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies 🔨
      run: |
        python -m pip install --upgrade pip
        pip install .
        # Install numpy first to ensure compatible versions
        pip install --upgrade numpy
        # Force reinstall of tables to ensure binary compatibility with numpy
        pip install --force-reinstall --no-cache-dir "tables>=3.10.0"
        pip install --upgrade-strategy only-if-needed pandas pyarrow
        pip install --upgrade-strategy only-if-needed flake8 black mypy data-science-types  # code quality related

    - name: Run tests
      run: |
        python -W ignore:ResourceWarning -m unittest

    - name: Code formatting (black)
      if: always()
      run: |
        black --check qnorm/ tests/

    - name: Code formatting (flake8)
      if: always()
      run: |
        flake8 qnorm/ tests/

#    (I can't get) mypy working with singledispatch and overload
#    - name: Code annotation (mypy)
#      run: |
#        mypy --config-file pyproject.toml --always-true=pandas_import ./qnorm/
